# Generated by Django 4.2.1 on 2023-06-08 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Mail del profesor')),
                ('celular', models.CharField(max_length=15, null=True)),
                ('telefono', models.CharField(default='', max_length=15)),
                ('egreso', models.IntegerField(default=2009)),
                ('fecha_contratacion', models.DateField(verbose_name=datetime.date(2023, 6, 8))),
            ],
        ),
    ]
